// <auto-generated />
namespace ESH_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DoctorStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoctorStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202304100733225_DoctorStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
