// <auto-generated />
namespace ESH_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _depHost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_depHost));
        
        string IMigrationMetadata.Id
        {
            get { return "202304101113376__depHost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
